package com.tierraburritoservidor.domain.model;

public enum Ingredientes {
    STEAK, CARNITAS, CARNE_BBQ, POLLO, ARROZ_BLANCO, ARROZ_INTEGRAL, FRIJOLES, VERDURAS,
    PICO_DE_GALLO, SALSA_DE_QUESO, SALSA_CHIPOTLE, CREMA_AGRIA, SALSA_666, SALSA_MEDIA,
    SALSA_VERDE, MAIZ, JALAPENOS, QUESO_RALLADO, GUACAMOLE, LECHUGA
}
